# -- judge.toml --
# 这个文件负责告诉评测姬你需要怎么评测你的程序

# 我们的评测标识符是 lexer
[jobs.lab6]
# 使用 Dockerfile 来源，路径就是当前文件夹
image = { source = "dockerfile", path = "." }

# 假如你用的是 Java
run = [
  # 运行程序
  "java -classpath ./out:./antlr-4.9.2-complete.jar Test $input $ir",
]